[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/db.js"]

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[functions."send-reminders"]
  schedule = "*/5 * * * *"
